# -*- coding: utf-8 -*-
"""Heart disease data visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-S610APyGhl7nFxqgUKyvCnV2hpxiC2J
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the Heart Disease dataset into a Pandas DataFrame
data = pd.read_csv('/content/heart_cleveland_upload.csv')


# Scatter plot
plt.scatter(data['age'], data['chol'], alpha=0.5)
plt.xlabel('Age (years)')
plt.ylabel('Cholesterol (mg/dL)')
plt.title('Age vs Cholesterol Scatter Plot')
plt.legend(['Cholesterol (mg/dL)'])
plt.show()

# Histogram
plt.hist(data['trestbps'], bins=10)
plt.xlabel('Resting Blood Pressure (mmHg)')
plt.ylabel('Frequency')
plt.title('Resting Blood Pressure Histogram')
plt.legend(['Frequency'])
plt.show()

# Bar plot
sex_counts = data['sex'].value_counts()
plt.bar(sex_counts.index, sex_counts.values)
plt.xlabel('Sex')
plt.ylabel('Count')
plt.title('Sex Distribution Bar Plot')
plt.legend(['Count'])
plt.show()

# Box plot
plt.boxplot(data['thalach'], vert=False)
plt.xlabel('Maximum Heart Rate Achieved')
plt.title('Maximum Heart Rate Achieved Box Plot')
plt.show()

print(data)

# Function to create a heatmap
def plot_heatmap(data):
    plt.figure(figsize=(10, 8))
    sns.heatmap(data.corr(), annot=True, cmap='coolwarm')
    plt.title('Correlations between features in the Heart Disease dataset')
    plt.xlabel('Feature')
    plt.ylabel('Correlation')

# Function to create a multiline chart
def plot_multiline(data):
    plt.figure(figsize=(10, 8))
    sns.lineplot(data=data[['age', 'trestbps', 'chol']], dashes=False)
    plt.title('Variations of age, resting blood pressure, and serum cholesterol over the dataset instances')
    plt.xlabel('Instance')
    plt.ylabel('Value')
    plt.legend(['Age', 'Resting Blood Pressure', 'Serum Cholesterol'])

# Call the functions to create the plots
plot_heatmap(data)
plot_multiline(data)